import { ramp } from "./gen.mjs";
import {
  SEVERITY,
  ACCENT_HUE,
  THEME_HUE,
  FILL,
  TRACK,
  RING,
  sevHex,
} from "./sev.mjs";

const S = (r, step) => r[step - 1]; // 1-indexed steps, as the sources number them

// Geometry and material per theme. Not colour, but they belong with the token
// block so a theme is defined in one place.
const SHAPE = {
  glass: { radius: "22px", blur: "blur(26px) saturate(180%)" },
  bento: { radius: "16px", blur: "none" },
  minimal: { radius: "10px", blur: "blur(10px)" },
  console: { radius: "8px", blur: "none" },
};

function themeTokens(theme, mode) {
  const n = ramp(THEME_HUE[theme], { mode });
  const alpha = theme === "glass" ? 0.82 : theme === "minimal" ? 0.9 : 1;
  const surface =
    alpha === 1
      ? S(n, 2)
      : `color-mix(in srgb, ${S(n, 2)} ${Math.round(alpha * 100)}%, transparent)`;
  return [
    `  --w-surface: ${surface};`,
    `  --w-surface-2: ${S(n, 3)};`,
    `  --w-track: ${S(n, TRACK + 1)};`,
    `  --w-ring: ${S(n, RING + 1)};`,
    `  --w-hair: ${mode === "light" ? "rgba(255,255,255,0.7)" : `${S(n, 6)}`};`,
    `  --w-ink: ${S(n, 12)};`,
    `  --w-ink-2: ${S(n, 11)};`,
    `  --w-ink-3: ${S(n, 10)};`,
    `  --st-warn: ${sevHex(mode, "warn")};`,
    `  --st-serious: ${sevHex(mode, "serious")};`,
    `  --st-crit: ${sevHex(mode, "crit")};`,
    `  --w-radius: ${SHAPE[theme].radius};`,
    `  --w-blur: ${SHAPE[theme].blur};`,
    `  --w-shadow: 0 ${mode === "light" ? "18px 44px -14px" : "24px 60px -16px"} ${
      mode === "light" ? "rgba(31,31,38,0.34)" : "rgba(0,0,0,0.7)"
    };`,
  ].join("\n");
}

const accentPairs = Object.entries(ACCENT_HUE).map(([name, hue]) => {
  const l = ramp(hue, { accent: true, mode: "light" })[FILL];
  const d = ramp(hue, { accent: true, mode: "dark" })[FILL];
  return `:root[data-accent="${name}"] {\n  --accent-l: ${l};\n  --accent-d: ${d};\n}`;
});

// Glass, Bento and Minimal follow the system appearance. Console is a
// terminal look and is dark in both modes on purpose, so it is emitted from
// the dark ramp twice rather than following prefers-color-scheme.
// Appearance is an explicit choice, not just the system setting: bare :root is
// light, and the dark values are declared twice — once behind
// prefers-color-scheme for "system", once behind [data-mode="dark"] so the
// in-app control wins in both directions.
const out = [];
out.push(
  "/* GENERATED by scripts/color/emit.mjs — see docs/COLOR.md. Do not hand-edit. */",
);

function block(selector, theme, mode, extra = []) {
  out.push(`${selector} {`);
  out.push(themeTokens(theme, mode));
  for (const line of extra) out.push(line);
  out.push("}");
}

function themeBlocks(theme) {
  const sel =
    theme === "glass" ? ":root" : `:root[data-widget-theme="${theme}"]`;
  const accentLight = theme === "glass" ? ["  --accent: var(--accent-l);"] : [];
  const accentDark = theme === "glass" ? ["  --accent: var(--accent-d);"] : [];
  block(sel, theme, "light", accentLight);
  out.push("@media (prefers-color-scheme: dark) {");
  block(`  ${sel}:not([data-mode="light"])`, theme, "dark", accentDark);
  out.push("}");
  block(`${sel}[data-mode="dark"]`, theme, "dark", accentDark);
}

for (const theme of ["glass", "bento", "minimal", "console"])
  themeBlocks(theme);

out.push(
  Object.entries(ACCENT_HUE)
    .map(([name, hue]) => {
      const l = ramp(hue, { accent: true, mode: "light" })[FILL];
      const d = ramp(hue, { accent: true, mode: "dark" })[FILL];
      return `:root[data-accent="${name}"] {\n  --accent-l: ${l};\n  --accent-d: ${d};\n}`;
    })
    .join("\n"),
);

console.log(out.join("\n"));
